// Auth Login Actiontypes
export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_DATA = 'USER_DATA';
export const USER_FROM_MOBILE_NUMBER = 'USER_FROM_MOBILE_NUMBER';
export const SAVE_USER_ID_WHEN_FORGOT_PASSWORD = 'SAVE_USER_ID_WHEN_FORGOT_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';

// Homepage Product ActionTypes
export const GET_FEATURED_PRODUCTS = 'GET_FEATURED_PRODUCTS';
export const GET_CHOICE_PRODUCT = 'GET_CHOICE_PRODUCT';
export const EMPTY_REDUCER = 'EMPTY_REDUCER';

export const HOME_EXPLORE_CATEGORY = 'HOME_EXPLORE_CATEGORY';
export const CATEGORY_EXPLORE_CATEGORY = 'CATEGORY_EXPLORE_CATEGORY';
export const SEPARATE_CATEGORY = 'SEPARATE_CATEGORY';
export const HOME_TRENDS_MONTH = 'HOME_TRENDS_MONTH';
export const HOME_DISCOUNTED_PRODUCTS = 'HOME_DISCOUNTED_PRODUCTS';
export const HOME_FEATURED_PRODUCTS = 'HOME_FEATURED_PRODUCTS';
export const HOME_LATEST_PRODUCTS = 'HOME_LATEST_PRODUCTS';
export const HOME_TREND_BANNER = 'HOME_TREND_BANNER';



export const ADD_TO_CART = 'ADD_TO_CART';
export const MINUS_FROM_CART = 'MINUS_FROM_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DELETE_THE_CART = 'DELETE_THE_CART';
export const ADD_SHIPMENT_CHARGES = 'ADD_SHIPMENT_CHARGES';

export const PENDING_ORDERS = 'PENDING_ORDERS';
export const CANCELLED_ORDERS = 'CANCELLED_ORDERS';
export const EXCHANGE_ORDERS = 'EXCHANGE_ORDERS';
export const RETURN_ORDERS = 'RETURN_ORDERS';

export const WIHSLIST_ADDITION = 'WIHSLIST_ADDITION';
export const WISHLISHT_DELETION = 'WISHLISHT_DELETION';
export const WISHLISHT_GET_ALL = 'WISHLISHT_GET_ALL';

export const GET_ABOUT_US_CONTENT = 'GET_ABOUT_US_CONTENT';
export const SEARCH_ALL_PRODUCTS = 'SEARCH_ALL_PRODUCTS';