export const GET_ALL_DATA = 'GET_ALL_DATA';

export const ADD_TO_CART = 'ADD_TO_CART';
export const MINUS_FROM_CART = 'MINUS_FROM_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DELETE_THE_CART = 'DELETE_THE_CART';

export const WIHSLIST_ADDITION = 'WIHSLIST_ADDITION';
export const WISHLISHT_DELETION = 'WISHLISHT_DELETION';
export const WISHLISHT_GET_ALL = 'WISHLISHT_GET_ALL';